### ISSUE TITLE
Anchor tag on Lily only fills half the figure

### ISSUE THREAD

**Issue by steve-kasica** [codrops/HoverEffectIdeas#1]
The anchor tag in the Lily effect only takes up the bottom half of `figure.effect-lily`, although the pointer cursor, indicating a link, applies to the entire figure. Here's what I see when I inspect the node in Chrome on OS X.
![screen shot 2014-10-18 at 7 00 53 pm](https://cloud.githubusercontent.com/assets/2933702/4691666/6b859f20-572b-11e4-8df4-f33967fb6cc6.png)
It seems like it's caused by the height attribute on the CSS style `figure.effect-lily figcaption`. It's only set to 50%. Of course, changing it to 100% fill the contain, but also screws up the text's position.

**Comment by crnacura** [comment]
Fixed in the new version. Thanks a lot!
