### ISSUE TITLE
Confusing CSS

### ISSUE THREAD

**Issue by miljan-aleksic** [codrops/HoverEffectIdeas#3]
First of all thank you for this awesome examples :)

I have found some difficulties integrating it because [this](https://github.com/codrops/HoverEffectIdeas/blob/master/css/demo.css#L12) necessary CSS is in the demo.css. If you try to copy only the set1.css it will not work well because the box-sizing rule is missing.

The effects should work even if you don't load the demo.css or normalize.css file. My tests were with Chico effect, maybe others do work fine.

Last, [this](https://github.com/codrops/HoverEffectIdeas/blob/master/css/set1.css#L1147) group of code, also present in set2.css should be moved to demo.css.

**Comment by crnacura** [comment]
The box-sizing rule is necessary, yes, but I don't want to repeat it throughout the set style(s). If you want one specific effect, you'll need to add that to your CSS along with the common styles for the figures and the effect file (and of course all the font styles etc.). You would not use the whole set1.css or set2.css anyway, you'll need to do this integration step where you take what you need and adjust it to your context.  
The media query for the content would be better in the demo.css. I'll correct that. Thanks for your feedback.

**Comment by miljan-aleksic** [comment]
I'm just suggesting to save others the time on finding out why is not working if you apply the common figure and specific effect css rules. If you are not aware of the box-sizing rule you could spend hours or give up if not experienced enough.

I understand, maybe you could add, but leave commented, the box-sizing rule in the set files so anyone copying it will notice it.

**Comment by crnacura** [comment]
The box-sizing rule has almost become a standard so I assume that everybody has it in their projects but yes, I agree, a comment will save time for the ones who don't. Thx.

**Comment by miljan-aleksic** [comment]
Assuming always leads to mistakes :) Keep up the amazing job! Pozdrav

**Comment by crnacura** [comment]
:+1:
