### ISSUE TITLE
Lack of text fade animation

### ISSUE THREAD

**Issue by peterkos** [codrops/HoverEffectIdeas#4]
When hovering over Romeo, the text jarringly changes to white instead of fading in.  
![romeo_lag2](https://cloud.githubusercontent.com/assets/2782749/4861058/0cba7e74-60ff-11e4-834d-4973c353549f.gif)

**Comment by crnacura** [comment]
Romeo does not have a transition like that at all... the text is white in the beginning and stays the same. Which browser and OS are you using? This looks like a z-index/perspective issue to me.

**Comment by peterkos** [comment]
Yosemite 10.10, Safari 8.0 (10600.1.25)
(Only seems to happen in Safari... Chrome/Firefox work fine)

**Comment by crnacura** [comment]
It had indeed to do with the perspective. I've changed it to scale the image instead and it should work fine now (see last commit). Thx

**Comment by peterkos** [comment]
Works great!
